"""
core - A Model Context Protocol (MCP) server that enables chatbots to query and monitor Kubernetes (k3s) clusters. The server provides tools for checking cluster health, pod status, resource usage, logs, and other cluster information via a standardized MCP interface.

Version: 0.1.0
"""

__version__ = "0.1.0"
__author__ = "Generated by meta-system"

# Package exports
__all__ = []
