"""Bug triage agent."""

from typing import Dict, Any, List
from pathlib import Path

from mcp_k3s_monitor.agents.base_agent import BaseAgent


class BugAgent(BaseAgent):
    """
    Agent for triaging bug reports.

    Analyzes:
    - Failed pods and error logs
    - Recent cluster events
    - Potential root causes
    - Affected services
    """

    def __init__(self, config):
        super().__init__(config, agent_type="bug")

    def get_agent_name(self) -> str:
        return "Bug Triage Agent"

    def get_cluster_query_prompt(self, issue_data: Dict[str, Any]) -> str:
        return f"""
You are a Bug Triage Agent investigating a bug report in a k3s cluster.

Analyze the following:
1. Failed pods and their status
2. Recent error events in the cluster
3. Logs from affected pods
4. Potential root causes based on symptoms
5. Urgency/severity assessment
6. Suggested debugging steps

Provide a structured triage with:
- Bug severity (Critical/High/Medium/Low)
- Affected components
- Root cause hypothesis
- Debugging steps
- Quick fixes (if available)
"""

    def get_workflow_template(self) -> str:
        return str(self.config.workflows_dir / "templates" / "bug_workflow.py")

    async def _query_cluster(self, issue: Dict[str, Any]) -> Dict[str, Any]:
        """Enhanced cluster query for bug triage."""
        base_data = await super()._query_cluster(issue)

        # Add bug-specific queries
        try:
            # Get failed pods
            all_pods = base_data.get("pods", [])
            failed_pods = [p for p in all_pods if p.get("status") != "Running"]

            # Get logs from failed pods (first 5)
            pod_logs = {}
            for pod in failed_pods[:5]:
                pod_name = pod.get("name")
                namespace = pod.get("namespace", "default")
                try:
                    logs = self.mcp_client.get_pod_logs(
                        pod_name=pod_name,
                        namespace=namespace,
                        lines=100,
                    )
                    pod_logs[pod_name] = logs
                except Exception as e:
                    self.logger.warning(f"Could not get logs for {pod_name}: {e}")

            base_data["failed_pods"] = failed_pods
            base_data["pod_logs"] = pod_logs

        except Exception as e:
            self.logger.error(f"Error in bug-specific queries: {e}")

        return base_data

    def _format_github_comment(
        self,
        analysis: Dict[str, Any],
        report_path: Path,
    ) -> str:
        severity = analysis.get("severity", "Unknown")
        root_cause = analysis.get("root_cause", "Under investigation")
        steps = analysis.get("debugging_steps", [])

        severity_emoji = {
            "Critical": "🔴",
            "High": "🟠",
            "Medium": "🟡",
            "Low": "🟢",
        }.get(severity, "❓")

        comment = f"""## {severity_emoji} Bug Triage Report

**Severity:** `{severity}`

**Root Cause Hypothesis:**
{root_cause}

### 🔍 Debugging Steps
"""
        for i, step in enumerate(steps, 1):
            comment += f"{i}. {step}\n"

        comment += f"""
### 📊 Cluster Analysis
Failed pods and error logs have been analyzed.

[📈 View detailed HTML report]({report_path})

---
*Generated by Bug Triage Agent* 🤖
"""
        return comment
