"""Maintenance/chore agent."""

from typing import Dict, Any
from pathlib import Path

from mcp_k3s_monitor.agents.base_agent import BaseAgent


class ChoreAgent(BaseAgent):
    """
    Agent for maintenance and operational tasks.

    Analyzes:
    - Resource optimization opportunities
    - Update/upgrade requirements
    - Configuration drift
    - Best practice compliance
    """

    def __init__(self, config):
        super().__init__(config, agent_type="chore")

    def get_agent_name(self) -> str:
        return "Maintenance Agent"

    def get_cluster_query_prompt(self, issue_data: Dict[str, Any]) -> str:
        return f"""
You are a Maintenance Agent handling operational tasks for a k3s cluster.

Analyze the following:
1. Current cluster configuration
2. Resource utilization and optimization opportunities
3. Update/upgrade recommendations
4. Best practice compliance
5. Security considerations
6. Automation opportunities

Provide a structured maintenance plan with:
- Current state assessment
- Recommended changes
- Impact analysis
- Implementation steps
- Rollback plan
"""

    def get_workflow_template(self) -> str:
        return str(self.config.workflows_dir / "templates" / "chore_workflow.sh")

    def _format_github_comment(
        self,
        analysis: Dict[str, Any],
        report_path: Path,
    ) -> str:
        recommendations = analysis.get("recommendations", [])
        impact = analysis.get("impact", "Low")

        impact_emoji = {
            "High": "🔴",
            "Medium": "🟡",
            "Low": "🟢",
        }.get(impact, "❓")

        comment = f"""## {impact_emoji} Maintenance Plan

**Impact:** `{impact}`

### 🛠️ Recommended Actions
"""
        for i, rec in enumerate(recommendations, 1):
            comment += f"{i}. {rec}\n"

        comment += f"""
### 📊 Cluster Assessment
Current configuration and optimization opportunities have been analyzed.

[📈 View detailed HTML report]({report_path})

---
*Generated by Maintenance Agent* 🤖
"""
        return comment
