"""Feature planning agent."""

from typing import Dict, Any
from pathlib import Path

from mcp_k3s_monitor.agents.base_agent import BaseAgent


class FeatureAgent(BaseAgent):
    """
    Agent for processing feature requests.

    Analyzes:
    - Current cluster capacity
    - Resource availability for new features
    - Recommended deployment strategy
    """

    def __init__(self, config):
        super().__init__(config, agent_type="feature")

    def get_agent_name(self) -> str:
        return "Feature Planning Agent"

    def get_cluster_query_prompt(self, issue_data: Dict[str, Any]) -> str:
        return f"""
You are a Feature Planning Agent analyzing a feature request for a k3s cluster.

Analyze the following:
1. Current cluster capacity and resource availability
2. Whether the cluster can support this new feature
3. Recommended deployment strategy (namespace, replicas, resources)
4. Potential risks or conflicts with existing deployments
5. Suggested implementation steps

Provide a structured analysis with:
- Executive summary
- Resource impact assessment
- Implementation recommendations
- Risk assessment
"""

    def get_workflow_template(self) -> str:
        return str(self.config.workflows_dir / "templates" / "feature_workflow.sh")

    def _format_github_comment(
        self,
        analysis: Dict[str, Any],
        report_path: Path,
    ) -> str:
        summary = analysis.get("summary", "Analysis complete")
        recommendations = analysis.get("recommendations", [])

        comment = f"""## ✨ Feature Planning Analysis

**Summary:**
{summary}

### 📋 Recommendations
"""
        for i, rec in enumerate(recommendations, 1):
            comment += f"{i}. {rec}\n"

        comment += f"""
### 📊 Cluster Status
Current cluster health and capacity have been analyzed.

[📈 View detailed HTML report]({report_path})

---
*Generated by Feature Planning Agent* 🤖
"""
        return comment
